flowchart TD
  PS5[5V Battery]
  PS3F[3V_FILAMENT Buck]
  GND[Common Ground]

  RP[Feather RP2040]
  M0[Feather M0]
  CORE[WS2812B Core Strip 30px]

  SW1[Switch 1 to GND\nM0 Pin 2: On/Off]
  SW2[Switch 2 to GND\nM0 Pin 3: Previous]
  SW3[Switch 3 to GND\nM0 Pin 4: Next]

  SP1[Spark Filament 1\nRP2040 Pin 5 via MOSFET]
  SP2[Spark Filament 2\nRP2040 Pin 6 via MOSFET]
  SP3[Spark Filament 3\nRP2040 Pin 9 via MOSFET]
  SP4[Spark Filament 4\nRP2040 Pin 10 via MOSFET]
  PF[Pulse Filament\nRP2040 Pin 11 via MOSFET]

  BR[Beam R\nRP2040 Pin 12 via MOSFET]
  BG[Beam G\nRP2040 Pin 13 via MOSFET]
  BB[Beam B\nRP2040 Pin 14 via MOSFET]
  PEL[Peltier Enable\nRP2040 Pin 15 via MOSFET/Relay]

  PUMP[Peristaltic Pump\nRP2040 Pin 8 via MOSFET]
  CLAW[FP-S14B Servo\nRP2040 Pin 7]

  M0 -- Serial1 TX --> RP
  M0 -- Pin 13 Data --> CORE

  RP --> SP1
  RP --> SP2
  RP --> SP3
  RP --> SP4
  RP --> PF
  RP --> BR
  RP --> BG
  RP --> BB
  RP --> PEL
  RP --> PUMP
  RP --> CLAW

  M0 --- SW1
  M0 --- SW2
  M0 --- SW3

  PS5 --> RP
  PS5 --> M0
  PS5 --> CORE
  PS3F --> SP1
  PS3F --> SP2
  PS3F --> SP3
  PS3F --> SP4
  PS3F --> PF
  PS5 --> BR
  PS5 --> BG
  PS5 --> BB
  PS5 --> PEL
  PS5 --> PUMP
  PS5 --> CLAW

  GND --- RP
  GND --- M0
  GND --- CORE
  GND --- SW1
  GND --- SW2
  GND --- SW3
  GND --- PUMP
  GND --- CLAW
